// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

public type ErrorNotFound record {|
    *http:NotFound;
    Error body;
|};

public type ExpenseClaim record {
    *ExpenseClaimInput;
    string id;
    string employeeId;
    "pending"|"approved"|"rejected" status;
    string? rejectionReason?;
    boolean exported = false;
    string createdAt;
    string updatedAt;
};

public type inline_response_200 record {
    # total matching items
    int count;
    # relative URI of the next page
    string? next?;
    # relative URI of the previous page
    string? previous?;
    ExpenseClaim[] data;
};

public type Error record {
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
};

public type ExpenseClaimInput record {
    # claimed amount
    decimal amount;
    "Travel"|"Meals"|"Lodging"|"Office Supplies"|"Other" category;
    # what the expense was for
    string description;
    # date the expense was incurred
    string date;
    # uploaded receipt reference, optional
    string? receiptUrl?;
};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type ErrorForbidden record {|
    *http:Forbidden;
    Error body;
|};

public type ExpenseClaimOk record {|
    *http:Ok;
    ExpenseClaim body;
|};

public type claimId_reject_body record {
    # why the claim was rejected
    string reason;
};

public type ErrorUnauthorized record {|
    *http:Unauthorized;
    Error body;
|};
